### ISSUE TITLE
Insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by njwyatt** [webchain-network/wallet#131]
``` 
JsonRpcError: Insufficient funds for gas * price + value
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
    at new JsonRpcError (file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
    at file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
 ```

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Insufficient funds for gas * price + value
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
>     at new JsonRpcError (file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
>     at file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
> ```

Hi, please can you explain how to reproduce this error? If possible, could you try to reproduce it with new wallet release? Specify also the operating system.

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Insufficient funds for gas * price + value
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25480:30)
>     at new JsonRpcError (file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25509:116)
>     at file:///C:/Users/okanesatoshi/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:25546:19
> ```

Hi, please while proceeding with a transaction of MINTME Coin, don't change default settings of gas : 21000.
