### ISSUE TITLE
500error

### ISSUE THREAD

**Issue by innks** [webchain-network/wallet#177]
loading 500 error
I don't know why?
![20191222_205827](https://user-images.githubusercontent.com/25054152/71321659-3ce3a100-2500-11ea-9046-cd3653e53760.png)
![20191222_210057](https://user-images.githubusercontent.com/25054152/71321660-4240eb80-2500-11ea-987f-61b4edeef821.png)

**Comment by danielwebimp** [comment]
Please try to restart your application. And if necessary choose another remote node. This is should be OK that way.
