### ISSUE TITLE
Missing "Add token by contract"

### ISSUE THREAD

**Issue by strusty** [webchain-network/wallet#71]
Is this feature still available, or do we need to remain at 1.0 to use it?  Will it be restored, or was this an oversight?

**Comment by danielwebimp** [comment]
> Is this feature still available, or do we need to remain at 1.0 to use it? Will it be restored, or was this an oversight?

Yes this feature is available in the latest release. So you can use 1.0 and beside, you can install the latest version to compare that feature. If you are satisfy with this latest release then you can update your version to the latest one.

**Comment by danielwebimp** [comment]
@strusty  Hi, this feature has been added in the latest release. Thanks again for your contribution.
