### ISSUE TITLE
Invalid sender

### ISSUE THREAD

**Issue by Iulian85** [webchain-network/wallet#79]
``` 
JsonRpcError: Invalid sender
    at JsonRpcError.ExtendableBuiltin (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24430:30)
    at new JsonRpcError (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24459:116)
    at file:///opt/WebchainWallet/resources/app.asar/app/index.js:24496:19
 ```

**Comment by danielwebimp** [comment]
> ```
> JsonRpcError: Invalid sender
>     at JsonRpcError.ExtendableBuiltin (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24430:30)
>     at new JsonRpcError (file:///opt/WebchainWallet/resources/app.asar/app/index.js:24459:116)
>     at file:///opt/WebchainWallet/resources/app.asar/app/index.js:24496:19
> ```

Can you give more explanation about this issue? What have you done for it to appear?
If as a sender you've entered an address which is not correct, I think it has been fixed in this release, because now the sender's address is chosen among the addresses created or imported by the user.
