### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by pedangrusak** [webchain-network/wallet#99]
``` 
TypeError: Cannot read property 'type' of null
    at Object.title (file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:115834:35)
    at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216068:54
    at Array.forEach (<anonymous>)
    at printBuffer (file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216045:10)
    at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216373:31
    at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216404:16
    at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:113275:23
    at dispatch (file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216456:18)
    at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:11879:5
 ```

**Comment by danielwebimp** [comment]
> ```
> TypeError: Cannot read property 'type' of null
>     at Object.title (file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:115834:35)
>     at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216068:54
>     at Array.forEach (<anonymous>)
>     at printBuffer (file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216045:10)
>     at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216373:31
>     at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216404:16
>     at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:113275:23
>     at dispatch (file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:216456:18)
>     at file:///C:/Users/joekoe/AppData/Local/Programs/WebchainWallet/resources/app.asar/app/index.js:11879:5
> ```

Hi, please can you explain how to reproduce this error? If possible, could you try to reproduce it with new wallet release? Specify also the operating system.
